updating based on comments

diff --git a/modules/golang/golang b/modules/golang/golang
--- a/modules/golang/golang
+++ b/modules/golang/golang
@@ -3,7 +3,10 @@ compdef _golang go
 function _deps(){
 	app="go"
 
-	$(hash $app 2>/dev/null) || $(myzsh error "Couldn't find application ${app}" && return 1)
+	if ! hash $app 2>/dev/null; then
+		myzsh error "Couldn't find application ${app}"
+		return 1
+	fi
 }
 
 go () {
